### ISSUE TITLE
关于DataFixerUpper的一个建议

### ISSUE THREAD

**Issue by ghost** [ZhenNing-MOD/Deuterium#1]
randompatches的配置文件中可以直接禁用DFU（关于DFU的作用可以看看[这里](https://www.mcmod.cn/class/3449.html)），所以我个人认为LazyDFU模组（以及Smooth Boot）没有任何存在的必要。

**Comment by Ginsway** [comment]
感谢反馈，已添加至v1.1.2+1.16.5
